/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg9_carlosnuila;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Nuila
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearParada = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jt_nombreParada = new javax.swing.JTextField();
        jt_distancia = new javax.swing.JTextField();
        jt_angulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jb_CrearPARada = new javax.swing.JButton();
        jd_crearBus = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jt_numeroIdentificacion = new javax.swing.JTextField();
        jt_placa = new javax.swing.JTextField();
        jt_color = new javax.swing.JTextField();
        jt_velocidad = new javax.swing.JTextField();
        jb_CrearBUS = new javax.swing.JButton();
        jd_crearEstudiante = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jb_crearParada = new javax.swing.JButton();
        jb_crearBus = new javax.swing.JButton();
        jb_crearEstudiante = new javax.swing.JButton();

        jLabel1.setText("Nombre:");

        jLabel2.setText("Distancia:");

        jLabel3.setText("Ángulo:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Crear Parada");

        jb_CrearPARada.setText("Crear");
        jb_CrearPARada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CrearPARadaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crearParadaLayout = new javax.swing.GroupLayout(jd_crearParada.getContentPane());
        jd_crearParada.getContentPane().setLayout(jd_crearParadaLayout);
        jd_crearParadaLayout.setHorizontalGroup(
            jd_crearParadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearParadaLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jd_crearParadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_crearParadaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jt_nombreParada, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_crearParadaLayout.createSequentialGroup()
                        .addGroup(jd_crearParadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jd_crearParadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_distancia)
                            .addComponent(jt_angulo, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addGroup(jd_crearParadaLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jb_CrearPARada)))))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearParadaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(93, 93, 93))
        );
        jd_crearParadaLayout.setVerticalGroup(
            jd_crearParadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearParadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(23, 23, 23)
                .addGroup(jd_crearParadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jt_nombreParada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearParadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearParadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jt_angulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jb_CrearPARada)
                .addGap(21, 21, 21))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Crear AutoBus");

        jLabel6.setText("Número Identificación:");

        jLabel7.setText("Placa:");

        jLabel8.setText("Color:");

        jLabel9.setText("Velocidad:");

        jb_CrearBUS.setText("Crear");
        jb_CrearBUS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CrearBUSMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crearBusLayout = new javax.swing.GroupLayout(jd_crearBus.getContentPane());
        jd_crearBus.getContentPane().setLayout(jd_crearBusLayout);
        jd_crearBusLayout.setHorizontalGroup(
            jd_crearBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearBusLayout.createSequentialGroup()
                .addGroup(jd_crearBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearBusLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jd_crearBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_crearBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_numeroIdentificacion)
                            .addComponent(jt_placa)
                            .addComponent(jt_color)
                            .addComponent(jt_velocidad, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                    .addGroup(jd_crearBusLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel5))
                    .addGroup(jd_crearBusLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jb_CrearBUS)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jd_crearBusLayout.setVerticalGroup(
            jd_crearBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearBusLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addGap(37, 37, 37)
                .addGroup(jd_crearBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jt_numeroIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_crearBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_crearBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jb_CrearBUS)
                .addGap(26, 26, 26))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Crear Estudiante");

        jLabel11.setText("jLabel11");

        jLabel12.setText("jLabel12");

        jLabel13.setText("jLabel13");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout jd_crearEstudianteLayout = new javax.swing.GroupLayout(jd_crearEstudiante.getContentPane());
        jd_crearEstudiante.getContentPane().setLayout(jd_crearEstudianteLayout);
        jd_crearEstudianteLayout.setHorizontalGroup(
            jd_crearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearEstudianteLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(96, 96, 96))
            .addGroup(jd_crearEstudianteLayout.createSequentialGroup()
                .addGroup(jd_crearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearEstudianteLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jd_crearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)))
                    .addGroup(jd_crearEstudianteLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_crearEstudianteLayout.setVerticalGroup(
            jd_crearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearEstudianteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addGap(78, 78, 78)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_crearParada.setText("Crear Parada");
        jb_crearParada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearParadaMouseClicked(evt);
            }
        });

        jb_crearBus.setText("Crear AutoBus");
        jb_crearBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearBusMouseClicked(evt);
            }
        });

        jb_crearEstudiante.setText("Crear Estudiante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_crearEstudiante)
                    .addComponent(jb_crearBus)
                    .addComponent(jb_crearParada))
                .addContainerGap(422, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jb_crearParada)
                .addGap(18, 18, 18)
                .addComponent(jb_crearBus)
                .addGap(18, 18, 18)
                .addComponent(jb_crearEstudiante)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_crearParadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearParadaMouseClicked
        // TODO add your handling code here:
        jd_crearParada.pack();
        jd_crearParada.setModal(true);
        jd_crearParada.setLocationRelativeTo(this);
        jd_crearParada.setVisible(true);
    }//GEN-LAST:event_jb_crearParadaMouseClicked

    private void jb_CrearPARadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CrearPARadaMouseClicked
        // TODO add your handling code here:
        try {
            String nombre = jt_nombreParada.getText();
            double distancia = Double.parseDouble(jt_distancia.getText());
            double angulo = Math.toRadians(Double.parseDouble(jt_angulo.getText()));
            Parada nuevaParada = new Parada(nombre, distancia, angulo);
            listaParadas.add(nuevaParada);
            JOptionPane.showMessageDialog(jd_crearParada, "Se ha creado una parada");
            jt_nombreParada.setText("");
            jt_distancia.setText("");
            jt_angulo.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_crearParada, "Error fatal");
        }
    }//GEN-LAST:event_jb_CrearPARadaMouseClicked

    private void jb_CrearBUSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CrearBUSMouseClicked
        // TODO add your handling code here:
        try {
            int numeroIdentificacion = Integer.parseInt(jt_numeroIdentificacion.getText());
            String placa = jt_placa.getText();
            String color = jt_color.getText();
            double velocidad = Double.parseDouble(jt_velocidad.getText());
            AutoBus nuevoBus = new AutoBus(numeroIdentificacion, placa, color, velocidad);
            listaBuses.add(nuevoBus);
            JOptionPane.showMessageDialog(jd_crearParada, "Se ha creado un autobus");
            jt_numeroIdentificacion.setText("");
            jt_placa.setText("");
            jt_color.setText("");
            jt_velocidad.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_crearBus, "Error Fatal");
        }
    }//GEN-LAST:event_jb_CrearBUSMouseClicked

    private void jb_crearBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearBusMouseClicked
        // TODO add your handling code here:
        jd_crearBus.pack();
        jd_crearBus.setModal(true);
        jd_crearBus.setLocationRelativeTo(this);
        jd_crearBus.setVisible(true);
    }//GEN-LAST:event_jb_crearBusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    ArrayList<Parada> listaParadas = new ArrayList();
    ArrayList<AutoBus> listaBuses = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jb_CrearBUS;
    private javax.swing.JButton jb_CrearPARada;
    private javax.swing.JButton jb_crearBus;
    private javax.swing.JButton jb_crearEstudiante;
    private javax.swing.JButton jb_crearParada;
    private javax.swing.JDialog jd_crearBus;
    private javax.swing.JDialog jd_crearEstudiante;
    private javax.swing.JDialog jd_crearParada;
    private javax.swing.JTextField jt_angulo;
    private javax.swing.JTextField jt_color;
    private javax.swing.JTextField jt_distancia;
    private javax.swing.JTextField jt_nombreParada;
    private javax.swing.JTextField jt_numeroIdentificacion;
    private javax.swing.JTextField jt_placa;
    private javax.swing.JTextField jt_velocidad;
    // End of variables declaration//GEN-END:variables
}
